
["Beasts Configuration"]
	#true means spawns are on, false  means they are not
	"Tree Ent Spawning" = true
	"Hermit King Spawning" = true
	"Mummy Spawning" = true
	"Vile Gator Spawning" = true
	"Bone Stalker Spawning" = true
	"Piglin Executioner Spawning" = true
	"Mushlin Spitter Spawning" = true
	"Furnace Spawning" = true
	"Horseless Headsman Spawning" = true
	#1 is normal, 2 is doubled, 3 is tripled
	"Phoenix Egg Rarity" = 1.0
	#1 is normal, 2 is doubled, 3 is tripled
	"Sea Viper Egg Rarity" = 1.0
	"Witch Doctor Spawning" = true

["Beast Items Configuration"]
	#Determines the slowness level applied by the root
	"Root Slowness" = 1.0
	#the amount of time an enemy will be slowed by the root's attacks (in seconds)
	"Root Timer" = 4.0
	#Determines the level of speed granted when wearing the shellmet
	"Shellmet Speed" = 1.0
	#Determines the amount of seconds between each heal while holding the Frigid Horn
	"Frigid Horn Timer" = 10.0
	#Determines the amount of time before the viper fang ticks damage onto itself in seconds
	"Viper Fang Damage Timer" = 10.0
	#Determines the level of poison given to mobs with the gator tooth
	"Vile Gator Tooth Poison Level" = 1.0
	#Determines the amount of time a mob is effected with the gator tooth's poison
	"Vile Gator Tooth Timer" = 5.0
	#Determines how long a spawned phantom stalker will stay alive for (in seconds)
	"Tamer Stalker Timer" = 300.0
	#Sets the amount of seconds the player receives strength for after killing a mob (default is 2)
	"Executioner Cowl Strength" = 2.0
	#Sets the amount of health using the Spore Bundle will replenish your health to (default is 6)
	"Spore Bundle Healing" = 6.0
	#Sets the seconds the player has 'antidote' after using the Spore Bundle (Default is 20)
	"Spore Bundle Antidote Timer" = 20.0
	#Determines how quickly the Molten coal takes damage
	"Molten Coal Damage Timer" = 3.0
	#Determines the level of strength applied to you when wearing the pumpkin helmet
	"Pumpkin Helmet Strength Level" = 1.0
	#Determines the level of resistance granted by the Jungle Pendant
	"Jungle Pendant Resistance" = 1.0
	#Determines the duration of resistance granted to the player
	"Jungle Pendant Timer" = 6.0

["Rare Beasts Configuration"]
	#true means spawns are on, false means they are not
	"Rare Tree Ent Spawning" = true
	"Rare Hermit King Spawning" = true
	"Rare Mummy Spawning" = true
	"Rare Yeti Spawning" = true
	"Rare Vile Gator Spawning" = true
	"Rare Bone Stalker Spawning" = true
	"Rare Piglin Executioner Spawning" = true
	"Rare Mushlin Spitter Spawning" = true
	"Rare Furnace Spawning" = true
	"Scarecrow Spawning" = true
	#1 is normal, 2 is doubled, 3 is tripled
	"Rare Phoenix Egg Rarity" = 1.0
	"Rare Sea Viper Egg Rarity" = 1.0
	"Rare Witchdoctor Rarity" = true

["Beast Pit Configuration"]
	#Determines the max number of Beast pits that can be lit at any given time per world
	"Allowed Beast Pit Number" = 2.0
	#Determines how long the Beast Pit stays lit (in ticks, default is 300)
	"Beast Pit Lit Timer" = 100.0
	#NOT WORKING AT THE MOMENT
	"Beast Pit Spawning Radius" = 16.0

[Other]
	#Determines if beasts can spawn in modded biomes based off of temperature
	"Modded Biomes Support" = true

